name: Android CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Remove Termux-only Gradle properties
        run: |
          sed -i '/org.gradle.java.home/d' gradle.properties
          sed -i '/android.aapt2FromMavenOverride/d' gradle.properties

      - name: Build with Gradle
        run: ./gradlew build --no-daemon
