name: Android CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle

      - name: Verify Java version
        run: java -version

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle (override Termux properties)
        run: |
          ./gradlew build \
            -Dorg.gradle.java.home="" \
            -Dandroid.aapt2FromMavenOverride="" \
            --no-daemon
